bbs/max_range: 5.0

# transformation search range
bbs/min_tx: -10.0
bbs/max_tx: 10.0
bbs/min_ty: -10.0
bbs/max_ty: 10.0
bbs/min_theta: -3.15
bbs/max_theta: 3.15

# origin point in lla
bbs/origin_lat: 22.90893939
bbs/origin_lon: 113.2042001737

# global map config
# slice height range (map coordinate)
bbs/map_min_z: -0.5
bbs/map_max_z: 1.0
# 2D map params
bbs/map_width: 2048
bbs/map_height: 2048
bbs/map_resolution: 0.5
bbs/max_points_per_cell: 5
# precomp map pyramid
bbs/map_pyramid_level: 6

# scan slice height range (sensor coordinate)
bbs/scan_min_z: -0.5
bbs/scan_max_z: 0.5
